# Generated by Django 5.2.7 on 2025-11-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='text',
            new_name='option_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='score',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='option',
            name='index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Untitled Quiz', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
    ]
