# Generated by Django 5.2.7 on 2025-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_dream_company_studentprofile_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
