from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status
from .serializers import QuizSerializer

@api_view(['POST'])
def save_quiz(request):
    """
    Save quiz generated by external model into DB
    Expected JSON format:
    {
        "student": 1,
        "title": "AI Generated Quiz",
        "total_score": 0,
        "questions": [
            {
                "question_text": "What is 2+2?",
                "correct_option": "4",
                "options": [
                    {"option_text": "2"},
                    {"option_text": "3"},
                    {"option_text": "4"},
                    {"option_text": "5"}
                ]
            }
        ]
    }
    """
    serializer = QuizSerializer(data=request.data)
    if serializer.is_valid():
        quiz = serializer.save()
        return Response({"message": "Quiz stored successfully", "quiz_id": quiz.id}, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
